# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Order(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, items=None, id=None, status=None):  # noqa: E501
        """Order - a model defined in OpenAPI

        :param items: The items of this Order.  # noqa: E501
        :type items: str
        :param id: The id of this Order.  # noqa: E501
        :type id: int
        :param status: The status of this Order.  # noqa: E501
        :type status: str
        """
        self.openapi_types = {
            'items': str,
            'id': int,
            'status': str
        }

        self.attribute_map = {
            'items': 'items',
            'id': 'id',
            'status': 'status'
        }

        self._items = items
        self._id = id
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'Order':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Order of this Order.  # noqa: E501
        :rtype: Order
        """
        return util.deserialize_model(dikt, cls)

    @property
    def items(self):
        """Gets the items of this Order.


        :return: The items of this Order.
        :rtype: str
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this Order.


        :param items: The items of this Order.
        :type items: str
        """

        self._items = items

    @property
    def id(self):
        """Gets the id of this Order.


        :return: The id of this Order.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Order.


        :param id: The id of this Order.
        :type id: int
        """

        self._id = id

    @property
    def status(self):
        """Gets the status of this Order.

        Order Status  # noqa: E501

        :return: The status of this Order.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Order.

        Order Status  # noqa: E501

        :param status: The status of this Order.
        :type status: str
        """
        allowed_values = ["placed", "making", "complete", "delivered"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status
