openapi: 3.0.0
info:
  description: An API to interact with a Coffee Shop
  title: Simple Coffee Shop API
  version: 1.0.0
servers:
- description: Example API Service running locally
  url: http://localhost:8080/v3
tags:
- description: Access point to Coffee Shop Orders
  name: store
paths:
  /store/orders:
    get:
      description: Returns a list of json schema where each one describes a coffee
        order stored within the database.
      operationId: get_orders
      responses:
        "200":
          content:
            application/xml:
              schema:
                items:
                  $ref: '#/components/schemas/Order'
                type: array
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Order'
                type: array
          description: successful operation
      summary: Retrieve all records of coffee orders from the store.
      tags:
      - store
      x-openapi-router-controller: openapi_server.controllers.store_controller
    post:
      description: "Submit a coffee order and choose your drink type, whether or not\
        \ you would like milk, your drink temperature, and size."
      operationId: add_order
      parameters:
      - description: The name of type of coffee you want to order.
        explode: true
        in: query
        name: name
        required: true
        schema:
          enum:
          - latte
          - espresso
          - drip coffee
          type: string
        style: form
      - description: The size of coffee you want to order.
        explode: true
        in: query
        name: size
        required: false
        schema:
          default: medium
          enum:
          - small
          - medium
          - large
          type: string
        style: form
      - description: The temperature of coffee you want to order.
        explode: true
        in: query
        name: temperature
        required: false
        schema:
          default: hot
          enum:
          - hot
          - cold
          type: string
        style: form
      - description: The type of milk you want to order.
        explode: true
        in: query
        name: milk
        required: false
        schema:
          default: noMilk
          enum:
          - noMilk
          - whole
          - oat
          - soy
          type: string
        style: form
      responses:
        "200":
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Order'
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
          description: successful operation
      summary: Submit a new order for a coffee.
      tags:
      - store
      x-openapi-router-controller: openapi_server.controllers.store_controller
  /store/orders/status:
    get:
      description: Returns a list of json schema filtered by status where each returned
        schema describes a coffee order stored within the database.
      operationId: find_orders_by_status
      parameters:
      - deprecated: false
        description: A state that a coffee order can be in as it is fufilled
        explode: false
        in: query
        name: status
        required: true
        schema:
          enum:
          - placed
          - making
          - made
          - delivered
          type: string
        style: form
      responses:
        "200":
          content:
            application/xml:
              schema:
                items:
                  $ref: '#/components/schemas/Order'
                type: array
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Order'
                type: array
          description: successful operation
      summary: Finds orders by status
      tags:
      - store
      x-openapi-router-controller: openapi_server.controllers.store_controller
  /store/orders/{orderId}:
    delete:
      description: Deletes order record from database. The order must be identified
        by its ID.
      operationId: delete_order
      parameters:
      - description: ID of order to delete
        explode: false
        in: path
        name: orderId
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/xml:
              schema:
                type: string
          description: Successful deletion
        "404":
          description: ID not found in database
      summary: Deletes a record of an order.
      tags:
      - store
      x-openapi-router-controller: openapi_server.controllers.store_controller
    get:
      description: Returns all information regarding a single order.
      operationId: get_order_by_id
      parameters:
      - description: ID of order to return all information on.
        explode: false
        in: path
        name: orderId
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Order'
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
          description: successful operation
        "404":
          description: ID not found in database
      summary: Find order by ID
      tags:
      - store
      x-openapi-router-controller: openapi_server.controllers.store_controller
    patch:
      description: Change the status of a single order in the store. The order must
        be identified by its ID.
      operationId: update_order
      parameters:
      - description: ID of order to be updated
        explode: false
        in: path
        name: orderId
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      - description: new status to update order to
        explode: true
        in: query
        name: status
        required: true
        schema:
          enum:
          - placed
          - making
          - made
          - delivered
          type: string
        style: form
      responses:
        "200":
          content:
            application/xml:
              schema:
                items:
                  $ref: '#/components/schemas/Order'
                type: array
          description: Successful update
        "404":
          description: ID not found in database
      summary: Updates the status of an individual order.
      tags:
      - store
      x-openapi-router-controller: openapi_server.controllers.store_controller
  /store/orders/{orderId}/milktype/{milk}:
    patch:
      description: Change the type of milk ordered. The order must be identified by
        its ID.
      operationId: update_order_milk
      parameters:
      - description: ID of order that needs to be updated
        explode: false
        in: path
        name: orderId
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      - description: new milk type to update order to
        explode: false
        in: path
        name: milk
        required: true
        schema:
          enum:
          - noMilk
          - whole
          - oat
          - soy
          type: string
        style: simple
      responses:
        "200":
          content:
            application/xml:
              schema:
                items:
                  $ref: '#/components/schemas/Order'
                type: array
          description: Successful update
        "404":
          description: ID not found in database
      summary: Updates the milk type in the order
      tags:
      - store
      x-openapi-router-controller: openapi_server.controllers.store_controller
  /store/orders/{orderId}/nametype/{name}:
    patch:
      description: Changes the type of a coffee ordered. The order must be identified
        by its ID.
      operationId: update_order_coffee
      parameters:
      - description: ID of order whose type needs to be updated
        explode: false
        in: path
        name: orderId
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      - description: new coffee type to update order to
        explode: false
        in: path
        name: name
        required: true
        schema:
          enum:
          - latte
          - espresso
          - drip coffee
          type: string
        style: simple
      responses:
        "200":
          content:
            application/xml:
              schema:
                items:
                  $ref: '#/components/schemas/Order'
                type: array
          description: Successful update
        "404":
          description: ID not found in database
      summary: Updates the coffee type in the order
      tags:
      - store
      x-openapi-router-controller: openapi_server.controllers.store_controller
  /store/orders/{orderId}/sizetype/{size}:
    patch:
      description: Change the size of the order. The order must be identified by its
        ID.
      operationId: update_order_size
      parameters:
      - description: ID of order that needs to be updated
        explode: false
        in: path
        name: orderId
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      - description: new size to update order to
        explode: false
        in: path
        name: size
        required: true
        schema:
          enum:
          - small
          - medium
          - large
          type: string
        style: simple
      responses:
        "200":
          content:
            application/xml:
              schema:
                items:
                  $ref: '#/components/schemas/Order'
                type: array
          description: Successful update
        "404":
          description: ID not found in database
      summary: Updates the size of the drink ordered
      tags:
      - store
      x-openapi-router-controller: openapi_server.controllers.store_controller
  /store/orders/{orderId}/temptype/{temperature}:
    patch:
      description: Change the temperature of the order. The order must be identified
        by its ID.
      operationId: update_order_temp
      parameters:
      - description: ID of order that needs to be updated
        explode: false
        in: path
        name: orderId
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      - description: new temperature to update order to
        explode: false
        in: path
        name: temperature
        required: true
        schema:
          enum:
          - hot
          - cold
          type: string
        style: simple
      responses:
        "200":
          content:
            application/xml:
              schema:
                items:
                  $ref: '#/components/schemas/Order'
                type: array
          description: Successful update
        "404":
          description: ID not found in database
      summary: Updates the temperature of the order
      tags:
      - store
      x-openapi-router-controller: openapi_server.controllers.store_controller
components:
  schemas:
    Order:
      description: A coffee order from the coffee shop. Describes exactly one drink.
      example:
        size: small
        name: latte
        temperature: hot
        milk: noMilk
        id: 0
        status: placed
      properties:
        id:
          description: A unique ID number that identifies this specific coffee order.
          format: int64
          title: id
          type: integer
        name:
          description: The name of type of coffee you want to order.
          enum:
          - latte
          - espresso
          - drip coffee
          title: name
          type: string
        size:
          description: The size of coffee you want to order.
          enum:
          - small
          - medium
          - large
          title: size
          type: string
        temperature:
          description: The temperature of coffee you want to order.
          enum:
          - hot
          - cold
          title: temperature
          type: string
        milk:
          description: The type of milk you want to order.
          enum:
          - noMilk
          - whole
          - oat
          - soy
          title: milk
          type: string
        status:
          description: The status of your order
          enum:
          - placed
          - making
          - made
          - delivered
          title: status
          type: string
      title: Coffeeshop Coffee Order
      type: object
      xml:
        name: Order
